### ISSUE TITLE
Notification Feature: Push Notifications to alert users

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1055]
_As a user I should get actively pulled into the app with notifications in order to not miss new developments or required actions._

An overall notification feature should help users stay updated without the need to actively open the app and check data. Instead, both within the app (with some notification indicator) as well as through push notifications, the user should be automatically informed about new details.

-----
On a technical level, this feature includes:
- [x] Service to trigger push notifications in a PWA (if needed, including backend and external services)
- [x] UI to show details of notifications within the app and an "unread notifications" indicator
- [x] Configuration logic to allow users to enable/disable different types of notifications for their account individually
- Triggers for specific notifications for certain events:
  - [ ] notification when config is changed that affects certain behavior for users (e.g. a different pre-filter for the matching view)
  - [x] notification when a new/changed entity record matches a criteria (e.g. the current user has been added as the "assigned person" on a task record or a new participant with status "signed up through public form" has been added)
- in a future version:
  - [ ] notification when a planned date is reached (e.g. on the deadline of a task entity)
  - [ ] notification when an app update is available (to highlight new features)
  - [ ] emails in addition to push notifications

-----
Broken into user stories as implementation steps:

As a user I can
- [x] Aam-Digital/ndb-core#2662
- [x] Aam-Digital/ndb-core#2661
- [x] Aam-Digital/ndb-core#2660
- [x] Aam-Digital/ndb-core#2690
- [x] Aam-Digital/ndb-core#2696
- [x] Aam-Digital/ndb-core#2723
- [x] Aam-Digital/ndb-core#2724
- [x] Receive notification when an entity is updated
  - [x] Aam-Digital/ndb-core#2775
  - ~? support placeholders (e.g. "current user") in "entity update notification" rules~
- [x] Aam-Digital/ndb-core#2746
- [x] Aam-Digital/ndb-core#2754
- [x] Aam-Digital/ndb-core#2804

![Notifications drawio](https://github.com/user-attachments/assets/33fc4e90-dcef-4325-b822-9ff0eab641b8)

-----
# Remaining tasks:

### Open Issues (Frontend):
- [x] Aam-Digital/ndb-core#2847
- [x] Aam-Digital/ndb-core#2849
- [x] Aam-Digital/ndb-core#2850
- [ ] polish display of system notification message + events in frontend

### Open Issues (Backend):
- [x] filter operator for "in list" ("$elemMatch")
- [x] NotificationEvent structure with context (entityId of affected doc?)
- [x] Aam-Digital/aam-services#70
- [x] implement GET /device/:id endpoint to allow checks if a device is correctly registered: #2812
- [x] documentation of setup instructions
- [x] write unit tests for condition check function
- [ ] write e2e tests
- [x] code review

Later (v1.1)
- [ ] Aam-Digital/replication-backend#172 
- [ ] pass NotificationEvent._id in the push notification payload and handle this in frontend to navigate to relevant view
- [ ] Aam-Digital/ndb-core#2801

**Comment by TheSlimvReal** [comment]
As far as I know there are 2 possible options for this currently:

## 1. Web Push API 
You can send a notification message to a centralized server including the ID of the device where this notification should be triggered. This normally needs a backend service that handles the device IDs as well as the notification scheduling (maybe based on time or things happening in the database). The problem is that the central server can decide to drop a notification if e.g. too many notifications have been sent in the recent time.

## 2. Notification Triggers
From inside the web application notifications can be registered and scheduled. For the notification a so called _trigger_ can be defined that defines when the application should be shown e.g. show a notification on next Monday morning. This has the great benefit that no backend service is required but probably has high limitations in how these triggers can be defined. Might work well for simple time-bound reminders.

**Comment by TheSlimvReal** [comment]
I seems like the main difference is whether the user should also receive notifications while the app is not running. If this is the case then push notifications should be used. Otherwise, notifications are also an option.

See [this post](https://stackoverflow.com/a/34844729/10713841)

**Comment by Ayush8923** [comment]
I’ve documented the current behaviour and the proposed solution in this [Document](https://docs.google.com/document/d/1vFAQKuxTIgrwREEDYGQ-A0M75zpATDuBhD9VWIEF4x8/edit?tab=t.0) for better clarity and understanding.

**Comment by sleidig** [comment]
Open tasks from final testing 21.03.2025:

- [ ] show loading while trying to check API
- [ ] drawer should close after navigating to settings or event entity
- [ ] for Todo entities: no route (because opened in dialog normally) means they navigate to 404
- [ ] if push enable fails (e.g. permissions denied) the toggle remains active (on reload is inactive again) --> directly disable if registration fails
- [ ] change NotificationConfig:TEMPLATE to be stored instead a Config:NotificationConfigTemplate
- [ ] clicking system notification does not open the app/browser
