### ISSUE TITLE
Feature: User management

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#1339]
The user management solution should fulfill the following requirements.

User perspective:

- [x] #1341
- [x] #771 
- [ ] #1342
- [x] Offline login should still work -> #1340 
- [x] Auto-login with valid JWT should still work -> #1340 
- [x] Migrate existing user-base to Keycloak without them having to update their password -> #1340

Technical perspective:

- [x] JWT to authenticate against CouchDB, ReplicationMS and other potential services
- [x] System to provide different permissions for different services (file upload)
- [x] #1340
- [ ] Option to trigger scripts when users are added/updated/deleted (update a permission object)
