### ISSUE TITLE
Import Module: infer column mapping from column header names

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1942]
The new ImportColumnMappingComponent does not yet automatically map columns to entity properties. We used to infer mappings from the column headers of the imported data. When the column header matches the property label or id, that should be pre-selected as a mapping.

Suggested user story of functionality / requirements:
1. upload a csv file where (some) column headers in the first row exactly match the field name of our Child entity type
2. in the "column mapping" step of the Import Module, the system automatically pre-selects the field for those columns where the id or label of the entity type match
3. If more than one column matches the same field, only the first one is mapped

-----
### Implementation steps:

- [x] Create a simple service that can handle this logic and can be called from ImportMappingComponent
- [x] Write a set of unit tests for this scenario (imported data + entityType --> expected column mapping) for the service
- [x] Implement the automatic column mapping logic
- [x] test in app as part of the overall Import Module flow

sample import file: 
[sample-import.csv](https://github.com/user-attachments/files/16172395/sample-import.csv)
