### ISSUE TITLE
Setup Wizard: Configure Validators for fields

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#2118]
_sub-task of #2047 , #2057_

Allow users to configure "validators" for individual fields of an entity in the field-config popup, like setting a field as "required".

### Implementation steps
- [ ] extend existing UI component from PR #2057 (`AdminEntityFieldComponent`), create and include a new component to be shown in the "Advanced Options & Validation" tab
  - that component should display a form which will configure a `FormValidatorConfig` within the `EntitySchemaField` interface
  - should allow to add one or more validators from a list of available
- [ ] transform[ DynamicValidatorsService hard-coded list of validators](https://github.com/Aam-Digital/ndb-core/blob/9d906f2343bcd39022c4e63a837ace07fbc710f3/src/app/core/common-components/entity-form/dynamic-form-validators/dynamic-validators.service.ts#L50-L64) into a more specified interface for validators
- [ ] use the array of DynamicValidatorsService to dynamically display all available validators in the form
- [ ] add field to configure a validator, when required (e.g. defining the number for a "min" or "max" validator through a form field)

possible UI draft (suggestion):
![image](https://github.com/Aam-Digital/ndb-core/assets/1682541/d40a792d-98f2-4be0-86b5-3ef02d529bca)
