### ISSUE TITLE
Configuration instead of Code

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#222]
Looking at the big picture, we should have a clean separation of general features and specifics of individual user organisations. Only then can the system be used and adapted by several organisations while the code still remains reasonably maintainable.
My vision would be to let users (or consultants) build a customized interface through some visual form designer, rather than every minor change requiring code. That way, users would have more power to make everything fit perfectly and a lot of the duplication of similar stuff could disappear into an optimized configuration rather than clogging up our code base. Ideally the system should still allow fully coded parts so that the system remains as powerful and flexible.

Maybe a 3-tier system would make sense:
1. Custom Configuration of forms, names, etc.
2. "Building Blocks" to visualize and manage different types of things
3. Foundation System providing database, session, users, basic structure for navigation/dashboard/...

We already are on the path towards this. Some generalized components have become building blocks for others and the foundation is mostly working. If we continue in this direction, I would suggest that we step by step remove more of the scenario-dependent code (i.e. the Schools and Children modules) into configurable components.

-----
**Implementation**
- [x] configurable detail views & forms: #526
- [x] configurable list views & filters: #550
- [x] adaptations to the entities to configure additional fields in the config instead of class #513 (PR #536)
- [x] saving config in a database or deployment project - away from the general core repository and easy to switch for multiple instances #558
- _later: adding a UI to edit config from within the app itself_
