### ISSUE TITLE
App should request re-login if authentication expired / fails in background

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#2225]
We have a few bugs users experience from time to time which are related to the authentication of a user expiring in the app. Currently we do not explicitly handle such cases when a 401 error occurs:

- #935
- #2044
- this also has caused a file attachment upload to fail for a user

### Tasks for implementation (to be discussed):
- [x] Detect when the current access token expires and automatically get a new one using the refresh token
- [x] (if still necessary) Catch 401 errors and send people to login screen if the reason is an expired login (or show a popup: "Continue offline or login again?")
- [x] use overall interceptor in Angular to detect these errors? (and check if some are handled automtically because the refresh token then gets a new valid token)

**Comment by sleidig** [comment]
Related errors (in Sentry):
- No token received from Keycloak (after seeing 401 request failures to /db) [1](https://aam-digital.sentry.io/issues/4993207451/?project=1242399&query=is%3Aunresolved+level%3Aerror&referrer=issue-stream&statsPeriod=7d&stream_index=1)
- Errors during HTTP requests for sync bubble up into various error logs (e.g. "Unexpected end of JSON input", "string did not match the expected pattern", "unexpected token '<' is not valid JSON") [1](https://aam-digital.sentry.io/issues/4709117795) [2](https://aam-digital.sentry.io/issues/4998405734) [3](https://aam-digital.sentry.io/issues/4911698763)
