### ISSUE TITLE
Improve Form Builder UX (Entity Details drag&drop)

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#2269]
The basic drag & drop editor to build entity details view (https://demo.aam-digital.com/admin/entity/Child/details) can be improved further:

- [ ] Sidebar with available fields should not scroll with main content (otherwise user has to drag the "new field" block long distance and scroll while dragging in long forms)
- [ ] form field groups (the boxes containing some fields) should allow to be drag&drop reordered
- [x] allow re-ordering of tabs

![image](https://github.com/Aam-Digital/ndb-core/assets/1682541/04b47bf5-a222-47d8-a364-1f3c370930a0)

### Implementation steps
- adapt `AdminEntityFormComponent` (for field groups and side bar)
- adapt `AdminTabsComponent` (for tabs)
