### ISSUE TITLE
refactor: Move Entity Attribute definition to db-based configuration 

### ISSUE THREAD

**Issue by tomwwinter** [Aam-Digital/ndb-core#2339]
Currently, some of the entity definition is just part of the ndb-core frontend. It is not possible to calculate the final entity from some backend service.

Target: Move all configuration logic to the database.
Needed for server-side schema calculation.

-----
## affected Entities:

**system internal (not customized by users):**
--> keep these in code; no action required

- ConfigurableEnum
- Config
- ImportMetadata
- SiteSettings
- PublicFormConfig
- ReportConfig
- SqsSchema
- ProgressDashboardConfig

**user-facing (often overwritten or extended):**

with some feature modules related code / fields:
--> keep as "stub" entity classes in code but move all fields into config also
- [ ] base `Entity`: created, updated, inactive, anonymized, ...  (probably this is something to handle separately and programmatically add in the backend)
- [ ] ... TimePeriod (as base entity for extensions)
- [x] Todo (incl. some calculations like `isOverdue` ...)
- [x] Note & EventNote (some custom methods and logical fields related to attendance, addChild, ...)
- [x] RecurringActivity (some fields are required for logic: `assignedTo`, `relatesTo`)
- [x] ChildSchoolRelation (specifically indexed via ChildrenService)

fully custom / demo types:
- [x] User
- [x] EducationalMaterial
- [x] Aser (incl. some calculations like `hasPassedEverything` ...)
- [x] HealthCheck (incl. some calculations like `bmi` ...)
- [x] School
- [x] HistoricalEntityData (has own service and component for indexing of docs --> see #262)
- [x] Child (incl. custom `isActive` --> remove that hidden logic; specifically indexed via ChildrenService)

-----
## TODOs:

- [x] move special methods of entity classes somewhere else, so that the class is not needed (?)
- [x] add necessary fields to config-fix for demo setup
- [x] remove classes and just make them interfaces for special components using them (?)
- [ ] protect those attributes that are required for logic from users changing the type, etc.
- [x] write script that finds fields that are used but not defined in "entity:*" block of config doc + write them into the config doc
- [x] remove logic for _isCustomizedField

**Comment by sleidig** [comment]
This is also a problem in the Admin UI as completely irrelevant fields from the hard-coded configs are showing up.

**Comment by sleidig** [comment]
Also see #2405 which is somewhat related for an improved entity config concept.
