### ISSUE TITLE
Create a fully functioning admin dashboard

### ISSUE THREAD

**Issue by codingfabi** [Aam-Digital/ndb-core#254]
To make the software completly usable, it is essential that some of the users are granted admin privileges and are able to do perform CRUD on users. Therefor, we should consider creating a functioning admin UI. For the UI, we should consider the following: 

- [x] A list that shows all users (use EntitySubrecordComponent) -> #63 
- [x] Within the List, an option to change the password of the user or even delete the user -> ? (related: #17 (password change))
- [x] A option to grant the user admin privileges
- [x] A button to create a new user using a form

Furthermore, we need to work out the following: 

- [ ] how to store the role of the user? AFAIK, it is stored as a boolen `isUser==true/falls`, is this the best way? (related: #128 closed origin discussion)
- [x] the admin pannel should only be accesable if the user is a admin
- [x] Can we use the existing admin interface and extend it? Or should we create a new one and use the exisiting as "super-admin-interface"

Due to the relevance  of this feature for the basic standalone use of the database by the social workers, this issue is getting set as High Priority.
Discussions about the details of implementation are welcome.

**Comment by codingfabi** [comment]
For development use the branch _adminUI_

**Comment by sleidig** [comment]
I added a few links to the list pointing to existing issues on these.

I would strongly suggest that we work for every point (also) with a separate issue and PR, so that we'll be able to merge things more regularly (even if the feature might not be visible to users yet). That would help us avoid stagnation and merge conflicts, imo.

**Comment by sleidig** [comment]
> * the admin pannel should only be accesable if the user is a admin

For this we have `AdminGuard` (assuming that the way we manage the admin status are safe, which is a general question); for usage see e.g. https://github.com/NGO-DB/ndb-core/blob/249f96fcff29f90ebca1a845043cfac94f3b38b4/src/app/navigation/navigation/navigation.component.ts#L42

Additionally, the final enforcement of access rights happens at the database on the server. (As everything else is happening locally on the user's machine it could always be circumvented or hacked more easily). Changing users is not possible for our normal CouchDB user accounts for example.


> * Can we use the existing admin interface and extend it? Or should we create a new one and use the exisiting as "super-admin-interface"

I think the user management should be a separate page, which would probably deserve its own top-level entry in the menu.

**Comment by codingfabi** [comment]
Okay so here is what @christophscheuing and I have done so far: 

- we created a list with all users only accessable for the users that are granted the admin role inside the application
- we made creation of new users possible (pleace note, that these users are no CouchDB-Users in the common sense but objucts with a id 'User:username". therefore, they are not stored in the commonly known /db/_users document.
- we made a work around in the entity-subrecord-component to make the creation of new user objects with the entity subrecord component possible. for more details, see PR #271

**Comment by sleidig** [comment]
while main points of this issue are not completely implemented yet, I am closing this issue now to focus the discussion in a single place.
The key remaining challenge is setting the password for new/existing users correctly. This is discussed in issue #17
