### ISSUE TITLE
Implement an EntitySchema system to avoid boilerplate index creation code etc.

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#260]
In an attempt to simplify creation of new Entity subclasses we will implement a EntitySchema system that allows EntityMapper to automatically handle relationships between Entities and make it unnecessary to write a lot of boilerplate code for creating indices (e.g. making the `ChildrenService` with all it's code duplications obsolete). 

Have a look at the PR #233 and especially the Unit Tests [entity.spec.ts](https://github.com/NGO-DB/ndb-core/blob/relational-pouch/src/app/entity/entity.spec.ts) and [entity-schema.spec.ts](https://github.com/NGO-DB/ndb-core/blob/relational-pouch/src/app/entity/entity-schema.spec.ts) to get examples of how it could be used.

Documentation: [Wiki: Creating new Entity types](https://github.com/NGO-DB/ndb-core/wiki/Creating-new-Entity-types), [Wiki: EntitySchema System](https://github.com/NGO-DB/ndb-core/wiki/EntitySchema-System)

### Sub-Tasks:
- [x] define basic structure and interfaces for `EntitySchema` (PR #233)
- [x] implement data transformations (entity object format <-> database format) for basic data types (PR #233)
- [x] use the schema in existing Entity subclasses (User, Child, School, ...) (PR #233)
- [ ] implement data transformations (entity object format <-> database format) for entity data type(s), automatically transform them between objects and reference IDs on save/load. (Issue #261)
- [ ] design automatic creation of indices based on the schema annotation and provide automatic querying methods for these (replacing the duplicated codes in `ChildrenService`, etc.) (Issue #262)
- [ ] design the schema to allow arrays of other datatypes
- [x] replace the explicit schema object that has to be defined and use code annotations on the attributes of the Entity classes instead (Issue #263)

Also see the discussion regarding `relational-pouch` that has led to this approach: #108

**Comment by sleidig** [comment]
closing this summary issue, as there are only two major topics left and those should be discussed independently.
