### ISSUE TITLE
SkillLab API integration

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#2623]
### Scenarios for matching:
1. A record for a person already exists in Aam Digital and needs to be “enriched” with data from skillmap.
2. No record for the person exists in Aam Digital, a completely new record is created using the data from skillmap.
3. (?) Person exists (is created) in Aam Digital - and is created in SkillMap?

We assume that, in most cases, scenario 1 will apply.

### Workflows for importing data:
two main functionalities / processes to pull the data:
- 1.1 Import data for individual records: For every record created, there could be a button that called “import profile from skillmap”
- 1.2 Import data in bulk: On the display of the people’s list, there is a button “import profiles from skillmap”. Aam then parses the data set from skillLab, finds matches, and completes missing data.
- 1.3 Import data for selected items: the user either selects groups of items or filters for a group of items and then clicks on the button “import profiels from skillLab”.

--> We will first implement (1.1) and then extend that core method to the other bulk flows

### Default Use Case (for user perspective):
1. User opens Individual's profile in Aam
2. User clicks "Load Skills" button
3. Aam connects to SkillLab:
   1. Aam Server connects & auth
   2. Aam Server requests data
   3. Aam Server finds match (or asks user?)
   4. (?) Aam Server create / update entity in Aam DB; or server sends data to user who then saves the entity
5. User sees skill records (or some message if nothing is found)

-----
## Implementation Steps:

**Critical paths:**
- matching of SkillMap record to Aam record
  - --> experiment manually with API
  - if many unmatchable records we may need some UI to manually match/search?
- UI / data structure to present skills in Aam
- Data structure to store skill-individual-relation (embedded in Individual? as separate relationship entities?)

**Questions**
- Do GIZ team have access to SkillMap?
- How are users using skills in Aam?
- How/when/whether to update skills of a participant?

-----
see 
- [GoogleDrive](https://drive.google.com/drive/u/0/folders/1Aaq1m4XJv0X09bpqNPBPH-OnAAtRK3MU)
- [Implementation Plan (GoogleSheet)](https://docs.google.com/spreadsheets/d/1qPOp0HEQz9P2vnFfAEv52H2Lz9UWIIB1q8DPR_Hi6_s/edit?usp=sharing)
- [ESCO Skill docs](https://esco.ec.europa.eu/de/classification/skill_main)

-----
## Remaining Sub-Tasks:

- Backend:
   - [x] SkillLab connection, data import, endpoints 
   - [x] tests
   - [x] code review
   - [x] permission / access control to limit users seeing the external data (new permission/role)
   - [x] optimizing search (with actual feedback from GIZ data)
   - [x] pagination of results
- Frontend: 
   - [x] bulk action
   - [x] fix bugs & UI glitches
   - [x] tests & API error handling
   - [x] code review
   - [x] pagination UI
   - [x] (maybe) some general refactorings

Later:
- [ ] detect & load updates from SkillLab ?
- [ ] create new entity in Aam for missing SkillLab matches
- [ ] import experiences & languages?
- [ ] multi-tenant support (connect multiple SkillLab projects independently with different tokens)

**Comment by sleidig** [comment]
**UI and requirements clarifications:**

Regarding scenario (3 - invite participant to Skill Platform via Aam Digital):
Is this a use case we should be working on during this iteration? Or should we only focus on (1) and (2) for now?
> Regarding the scenarios 3 below, my impression is that it is a variation of scenarios 1 or 2. Either the person will already exist on Aam or on Skill. We assume that few organizations will trigger an invitation into Skill to a person they have never met, which means that there will be some sort of data collection of a person before she/he receives an invitation into the Skill Tagging Platform.
> So far,  the other platform may not be ready to have APIs that pull data. This means that data collected in Aam cannot be pushed into the Skills platform, which hence means that data will have to be collected twice if the data is collected first on Aam.


Are users or staff members updating existing skill profiles in SkillLab regularly?
> Most users are not updating their profiles because we have not linked the Skills Platform with new activities in which career guidance officers or the like would engage the users with the Skills Platform. It has a function of transferring skills tagged to a training to a participant in that training. This happens manually, though. After this happens, it would be great if the update of skills can also appear in Aam.


What is the meaning of the different Skill Platform "Projects" that you have within their platform?
> The names of the projects reflect the organizations who provided invited users into the Skill Tagging Platform. Each organization got their own portal and can only see their own data.


----

How are users going to use the skill data within Aam Digital? Do you plan any interaction beyond seeing the skills of an individual listed in their profile in Aam Digital? If so, could you provide some simple sample scenarios (e.g. "User clicks A; sees B; does C; then does D")?
> We are interested to use the skills to filter and sort people, organizations, events, etc. by skill. Eventually one could also use the skills to determine suitability for an event, although that would require development in Aam that we won’t be able to do in this contract.


Are you planning to just use the "Skills" (ESCO ID + skill level) or also the "Experiences" (i.e. the jobs or studies from which the user got these skills from the Skill Tagging Platform).
> Being able to see the skills, the experiences related to these skills and languages would be great. That would be a good basis to work on eligibility screening to events or roles in the future. (although this won’t happen within this implementation iteration)

**Comment by sleidig** [comment]
In order to make entities filterable for the imported skills, we would currently need to add them directly on the entity itself. 

This makes it hard to also show related experiences and details however ... So that is an aspect to still plan and discuss further.

Possible UX flow (within the Entity Details view of an individual):
![image](https://github.com/user-attachments/assets/963085ec-731f-47ee-9e58-6cd7ca0bd37d)

**Comment by sleidig** [comment]
https://skilllab-integration.aam-digital.app/
