### ISSUE TITLE
create documentation

### ISSUE THREAD

**Issue by vlle1** [Aam-Digital/ndb-core#268]
# general todos
- [x] remove redundant documentation, keep number of places small.
- [x] make clear differentiations between documentation for developers (->github pages) and documentation for users (->github wiki)

# developer-oriented documentation
- [x] write instructions how to use compodoc in wiki #276 
- [ ] **document more classes using standard JSDoc** (see 'documentation coverage' in generated compodoc), this is automatically exported to the compodoc. #277 
- [x] automatically use documentation via github pages @TheSlimvReal 
- [x] transfer as much as possible from /doc/technical to markdown (/doc/compodoc_sources) #279 
- [ ] add graphic for routing to the compodoc (see https://compodoc.app/guides/routing.html) #278
- [x] change branch from where compodoc is generated in .travis.yml back to 'master'.
# user-oriented documentation
- [x] translate and add specification sheet
- [x] update functional requirements (in specification sheet) #280 
- [x] create 'how to' file from functional  requirements #281 
- [x] copy wiki files into '/doc/wiki' folder (wiki can later be automated)
- [x] **automate wiki**:  automatically add markdown files from 'doc/wiki' to github wiki page @TheSlimvReal

**Comment by sleidig** [comment]
So where are the docs on GitHub Pages actually? What's the URL?

It probably makes sense to close and delete the existing wiki completely (at least for developer documentation) in favour of the new docs.

**Comment by vlle1** [comment]
* you can find the new documentation in this github repository under http://aam-digital.github.io/ndb-core/ or just navigate in this repository to > Code > envrionment.
* we intend to use the github wiki not for developing the project but only for how to use the 'product'.

**Comment by sleidig** [comment]
I love the compodoc docs! :+1: 

I'd suggest to rename the compodoc section "developer wiki" to avoid confusions between that and the GitHub Wiki. Maybe the "developer wiki" section should actually become three sections (following https://www.divio.com/blog/documentation/): "Tutorials", "How Tos" and "Explanations" (maybe there are better titles for them).
Would you delete the GitHub Wiki pages if they are in compodocs, so that we don't keep parallel content?

Is it possible to move the generate sections (Modules, Classes, Injectables, Guards, Interfaces, Miscellaneous, Documentation Coverage) under a top-level menu entry called "Reference" (or a similar name)?

**Comment by vlle1** [comment]
hey, removing duplicate is part of this issue already, but I also moved the other ideas of you to another issue (see #293 )

**Comment by sleidig** [comment]
closing this general ticket: while some smaller tasks remain to be added the main effort is complete and with PR #320 merged the documentation looks quite clean and good now.
