### ISSUE TITLE
Automated Status-Updates based on linked entity

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#2694]
_As a user I want the system to keep related status of different records automatically up-to-date so that I don't forget and end up with inconsistent, outdated data._

## Scenario
- entity types: Mentor, Mentee, Mentorship
- Mentorship contains fields linking to a Mentor and a Mentee
- Mentorship "status" field with different dropdown options (e.g. "active", "finished")
- Mentee and Mentor "status" fields with different dropdown options (e.g. "open for mentorship", "in mentorship", "alumni")

## Goal
For users, the status of the Mentorship and its linked Mentee and Mentor are logically related. Updating the status of the Mentorship should automatically update the related Mentor's and Mentee's status as well:

1. When I create a new Mentorship, I want the linked Mentor's and Mentee's status to change to "in mentorship".
2.  When I change the Mentorship's status to "finished", I want the linked Mentor's and Mentee's status to change to "alumni".

### Edge cases
3. When the Mentor has a second Mentorship that is still active, I actually want to keep the Mentor's status as "in mentorship" even when "finishing" one of the Mentorships.
4. When I have talked to the Mentor before and she is willing to take up a new Mentorship again, I may want to change the Mentor's status to "open for mentorship" instead of "alumni".
5. When I have previously set the Mentor's status manually back to "open for mentorship" for some exceptional reason, I may want the Mentor's status to stay in that status instead of being changed to "alumni" when "finishing" the Mentorship.

--> User needs to be aware of the automated updates and have control over them to possible overrule the automation.

-----
# Suggested Functionality

## Semi-automatic status updates
After saving the Mentorship with a new status, the following process gets triggered automatically:
1. A dialog popup appears, listing affected linked status:
   1. "You have updated the _status_ of this record. The _status_ is linked to the following records' _status_. Do you want to update the following?" 
   2. within the dialog the affected linked records are listed
   3.  in our example:
       - Mentor _Jane Doe_ [current status: "in mentorship"] [new status: "alumni"]
       - Mentee _John Doe_ [current status: "open to mentorship"] [new status: "open to mentorship"]
   4. the "new status" field is an editable form field that allows to manually select any status from dropdown
   5. the "new status" is pre-filled with the default automation mapping (see configuration below)
   6. dialog buttons "Update related fields", "Do not update" let the user confirm the process
2. The system automatically edits and saves the affected records (Mentee, Mentor) according to the dialog result
3. The dialog is only shown if a field that is affecting such an automation rule is changed
   - Whenever an entity is saved, the system checks the entity schemas of all entity types
      - if the current entity type being saved is involved in any rule to update another type's field
      - if any of the fields involved in such a rule have been changed by the edits being saved right now. 

## Configuring automated fields
1. The Admin Entity Field dialog allows to configure this ("Edit data structures -> Details View & Fields -> Edit Field")
2. In the "Advanced Options" tab, the "Default Value" field offers a fourth type (in addition to the similar but different "inherited from linked record"): "Update based on changes in related record"
   ![Image](https://github.com/user-attachments/assets/5dd75785-21f1-4f81-a9b8-bc2c28be3833)

3. After toggling this type, the UI offers dropdowns of possible related records, similar to the existing "inherited from" mode:
   1. Dropdown offering all entity types that link to this entity type (e.g. when editing the field of the "Mentor" entity type, this will list the "Mentorship" entity type because the Mentorship has a field referencing a Mentor)
   2. After selecting the entity type (i), a button appears to open a configuration window to define a specific mapping/rule
4. The rule configuration window allows to select a field of the selected entity type "Update when this field changes"
   - only dropdown (configurable-enum) fields are allowed currently 
5. After selecting the field, the UI shows all items of that field's dropdown option listed below each other and a second column next to each shows a form field to let the user select the related status that should be auto-updated when the value on the left column gets set
   - e.g. similar to this layout: 
   ![Image](https://github.com/user-attachments/assets/ce3b88a4-3c1c-418c-9215-dd3891204dda)

## Generalized implementation
We do not want to implement narrowly hard-coded functionalities. This feature should be implemented to work for any number of entity relationships and any type and number of fields.

-----
# Implementation steps

- [x] Create a suite of unit tests covering this scenario:
   - `TestMentorship` and `TestMentee` with status fields and reference field (a one-to-one should probably be enough for testing)
   - test cases for
      - should ask to update mentee status when status of mentorship linking to it changes
      - should not ask to update mentee status when other field of mentorship linking to it changes
      - should not ask to update mentee status if status of mentorship linking to different mentee changes
      - ...?
- [x] Create a config structure to store the automation rules as part of an EntitySchemaField (and define a test config of this for the TestMentee.status field)
- [x] Extend Admin UI of "default value" field to configure the new mode
   - [x] Create component to configure specific mappings of source - target values for the automation
- [x] Create service and implement the logic to detect when a dialog should be shown (to be tested against the unit tests above)
   - [x] Implement logic to get the existing and calculate the new value
   - [x] Implement logic to update and save the affected entiti(es)
   - [x] this should also support arrays of linked entities (e.g. multiple mentees linked in the mentorship)
   - maybe debug this with log messages or unit tests
- [x] Create component for the confirmation dialog
- [x] Integrate service showing dialog into the entity form saving process

-----
# Possible extensions:
- show in the UI of the linked field (e.g. the Mentee) that this field is automated
- if changing that automated field (in the Mentee form), show a warning explaining that this is overwriting an automation
- integrate to also work when doing "bulk edit"

**Comment by Abhinegi2** [comment]
To integrate automation rules intoEntitySchemaField, a new optional property can be:
```
export interface EntitySchemaField {
  dataType?: string;
  isArray?: boolean;
  ..
  ..
 /**
 * automation rules that trigger updates in related entities when this field changes.
 */
 automationRules?: AutomationRuleConfig[];

}
```

AutomationRuleConfig can be:
```
interface AutomationRuleConfig {
  automatedCondition: AutomatedCondition;
  automatedActions: AutomatedAction[];
}

interface AutomatedCondition {
  field: string; (**or can be FormFieldConfig**)
  values: any[];
}

interface AutomatedAction {
  linkedEntity: string;
  linkedField: string;
  newValue: any;
}
```

**Comment by Abhinegi2** [comment]
Now I am thinking like this:

```
export interface DefaultValueConfig {
  mode: DefaultValueMode;
  value?: any;
  localAttribute?: string;
  field?: string;
  automatedConfigRule?: AutomatedConfigRule[];
}
```
And the automation rule configuration can be:
```
interface AutomatedConfigRule {
  relatedEntity: string;
  relatedField: string;
  automatedMapping: { [key: string]: string };
}
```
Here's how this configuration can be saved in the Mentorship schema:
```
{
  "status": {
    "dataType": "configurable-enum",
    "label": "Status",
    "defaultValue": {
      "mode": "automated",
      "automatedConfigRule": [
        {
          "relatedEntity": "Mentor",
          "relatedField": "status",
          "automatedMapping": {
            "active": "in mentorship",
            "finished": "alumni"
          }
        },
        {
          "relatedEntity": "Mentor",
          "relatedField": "someotherfield",
          "automatedMapping": {
            "active": "other value",
            "finished": "closed"
          }
        }
      ]
    }
  }
}
```
let me know now it make sense or if you have any other suggestion

**Comment by sleidig** [comment]
This sounds clear and logical to me 👍

**Comment by Abhinegi2** [comment]
While working on the confirmation dialog component, I created a draft UI. 

1. I just wanted to check—do we want to show a detailed view with affected records(eg. child name) and their corresponding field values(gender option), like this -


![Image](https://github.com/user-attachments/assets/4d316066-1dad-484b-8d6e-971b3f7a6a5b)


2. or should we keep it simpler? For example, just show a message like “16 children will be affected” along with a single field where the user can update the value for all of them.
like this 

![Image](https://github.com/user-attachments/assets/e309cc67-c333-47f1-b2bc-8a0ddbeb0a0a)

**Comment by sleidig** [comment]
Thanks for the mocks, @Abhinegi2 . Very helpful for discussion!

I think there may be cases where just one affected record is a special case, edited manually. So I vote for option 1. We should be able to use `EntityBlockComponent` with the ID of the affected record to display its "default" representation (usually the icon and name). And then as you outlined a form field each pre-filled with the suggested new status, where the user can manually edit before confirming

**Comment by sleidig** [comment]
https://docs.google.com/presentation/d/18UrRciLV0o161zKF-r8M3plIBnkKbalnekjVNwIPCL4/edit?usp=sharing

**Comment by Abhinegi2** [comment]
> Regarding the mapping of "when" - "then" values in the Admin UI:
> 
> I have collected feedback from our client's users and in the discussion realize a few further aspects.
> - They tend towards fixing the mentorship status and selecting mentee/mentor status that are updated by these.
> - Some use cases may have mappings where multipe triggers should set the field to the same value (e.g. maybe "finished" and "aborted" status of mentorship should both map to "alumni" status of mentee). In such cases the design with the mentorship as trigger fixed on the left also seems more clear to me.
> 
> Kindly requesting you to swap the layout of these two for now, @Abhinegi2 .
> 
> Also: maybe we can add "column headers" to clarify? e.g. "when related field changes to ..." and "then this field is updated to ..."

Sure let me make these changes.
Also I add the headers for better clearity.
