### ISSUE TITLE
Configure/Disable certain notifications for a user

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#2696]
To allow users to enable or disable various notification types in the UI:
- [x] Create the multi-select option on the user [profile page](https://demo.aam-digital.com/user-account), allowing users to select the notification types they want to receive.
- [x] Implement the Notification setting UI according to this suggested [UI](https://github.com/Aam-Digital/ndb-core/issues/2696#issuecomment-2531195353)

For details on the required database updates, here is the discussion:
https://github.com/Aam-Digital/ndb-core/issues/2690#issuecomment-2511143287

**Comment by sleidig** [comment]
This looks great! I like the individual toggling for each type but having the "where you receive" as a central setting separately.

For the "What notifications" section, I could imagine a listing if different active and standard notification types and then a button to "add new notification rule" for configuring an additional custom trigger (e.g. a very special filter to get informed about a sub-type of certain entities). A bit like this (as a sample of the logic, not necessarily for the exact UI):
![image](https://github.com/user-attachments/assets/4e1d04c1-063c-4402-9f2f-e2b6a1593be3)

Such custom notification triggers (in contrast to default general notification types) should also offer to get deleted rather than just deactivated.

**Comment by Abhinegi2** [comment]
@Ayush8923  
can we add some text like this -
<img width="822" alt="Image" src="https://github.com/user-attachments/assets/716694ea-4de8-47dc-87b3-2ede323dd838" />

**Comment by Ayush8923** [comment]
# TODOs for Notification UI Updates  

## Descriptions  
- [ ] Update the description for the Notification Settings top title.  
- [ ] Add a description to the `What notifications you receive` title.  
- [ ] Add a description to the `Where You Receive Notifications` title.  

## Dynamic Saving  
- [ ] Remove the Save and Cancel buttons and implement dynamic saving functionality.  

## Information Icons  
Add an information icon to the following:  
- [ ] Select Entity Type  
- [ ] Notification Condition  
- [ ] Toggle Button  
- [ ] Push Notification inside the `Where you receive notifications` section

## Default Settings  
- [ ] If no notification settings are selected by the user, add a default entry for each field.  

## Test Trigger Button  
- [ ] Add a `Test Trigger` button to each notification rule so users can preview how the notification will appear.  

## Section Updates  
- [ ] Update the `Where You Receive Notifications` section:  
  - [ ] Add Email Notifications with a `Coming Soon` label and keep it disabled.  

---

@sleidig @george-neha  I have added the todos for notification UI updates, please take a look and let me know if I missed anything.

**Comment by Ayush8923** [comment]
@sleidig @george-neha I have updated the notification settings UI according to the suggestions mentioned above. Could you please have a look and let me know if any updates or changes are needed? For reference, here is the screenshot.
1. 
<img width="1538" alt="image" src="https://github.com/user-attachments/assets/fdd2a9ec-053f-4075-acdc-45d2a8c8b353" />

2. 
<img width="1537" alt="image" src="https://github.com/user-attachments/assets/1f74a3d9-5675-447d-822b-a92ddbf0b6bf" />


Also, @george-neha, could you please share the updated descriptions for the fields listed below, so that I can update them here?
1. Description for the Notification Settings top title.
2. Description to the `What notifications you receive` title.

**Comment by Ayush8923** [comment]
@george-neha 
1. If the `Where you receive notifications` section is placed above the `What notification you receive` section, the latter will move below. In this scenario, users would still need to scroll down to add more notification rules. However, the What notification you receive section seems more important for users. What do you suggest/think?
2. Yes. For now, the `Notification Center` dropdown is disabled. However, as far as I have checked, the system has globally set the selected value's colour to black for better readability as we disable forms by default
