### ISSUE TITLE
Add explanations about current school and class to UI

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#591]
Several users have been confused with the current school and class of children and failed to update the school history in a way to update the current school+class.

**Context:**
the current school and class of a child is "calculated" from the school history based on the "From" and "To" dates. If "To" is in the past, the entry is not considered active and the current school remains empty if no other school history entry applies.
Users can leave the "To" field empty or set it to the end of the school year already. In both cases the app then shows the current class and school from that entry.

**TODO**
- [x] add tooltips or other guidance to explain to users how this works
- [x] add a warning when editing an existing entry to explain to users that usually they should add an additional school history entry for each year instead of updating the class in the existing entry.
- [x] add a warning / hint if no school is currently active (in the place above the list where otherwise the current school would be displayed), explaining that you need to add an entry for the current time period in the table below in order to associate the participant with a school.

**Comment by TheSlimvReal** [comment]
done in #1026
